/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LegoButton {
    }
}
declare global {
    interface HTMLLegoButtonElement extends Components.LegoButton, HTMLStencilElement {
    }
    var HTMLLegoButtonElement: {
        prototype: HTMLLegoButtonElement;
        new (): HTMLLegoButtonElement;
    };
    interface HTMLElementTagNameMap {
        "lego-button": HTMLLegoButtonElement;
    }
}
declare namespace LocalJSX {
    interface LegoButton {
    }
    interface IntrinsicElements {
        "lego-button": LegoButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lego-button": LocalJSX.LegoButton & JSXBase.HTMLAttributes<HTMLLegoButtonElement>;
        }
    }
}
